### ISSUE TITLE
when I update to Qt Creator 12.0.0,it's a tragic

### ISSUE THREAD

**Issue by guirongb** [fcitx/fcitx-qt5#56]
unfortunately I update to Qt Creator 12.0 
and can't rollback.
when i type a word , Creator crushed ....
fcitx-qt5  

platforminputcontexts/libfcitxplatforminputcontextplugin-qt6.so: symbol _ZN22QWindowSystemInterface22handleExtendedKeyEventEP7QWindowmN6QEvent4TypeEi6QFlagsIN2Qt16KeyboardModifierEEjjjRK7QStringbtb version Qt_6_PRIVATE_API not defined in file libQt6Gui.so.6 with link time reference

**Comment by faywong** [comment]
The QT Creator 12.0.2 in my Gentoo Linux workstation also crashes in launching, it absolutely caused by fcitx qt im module(after i removing /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so it won't crash any more)

```shell
Thread 1 "qtcreator" received signal SIGSEGV, Segmentation fault.
0x00007ffff647b9d0 in QObject::thread() const () from /usr/lib64/libQt6Core.so.6
(gdb) bt
#0  0x00007ffff647b9d0 in QObject::thread() const () at /usr/lib64/libQt6Core.so.6
#1  0x00007ffff64ca24b in QObject::QObject(QObjectPrivate&, QObject*) () at /usr/lib64/libQt6Core.so.6
#2  0x00007ffff2055731 in FcitxInputContextProxy::FcitxInputContextProxy(FcitxWatcher*, QObject*) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#3  0x00007ffff206f105 in FcitxQtICData::FcitxQtICData(FcitxWatcher*) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#4  0x00007ffff2077c0b in std::pair<QWindow* const, FcitxQtICData>::pair<QWindow*&, 0ul, FcitxWatcher*&, 0ul>(std::tuple<QWindow*&>&, std::tuple<FcitxWatcher*&>&, std::_Index_tuple<0ul>, std::_Index_tuple<0ul>) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#5  0x00007ffff20779c7 in std::pair<QWindow* const, FcitxQtICData>::pair<QWindow*&, FcitxWatcher*&>(std::piecewise_construct_t, std::tuple<QWindow*&>, std::tuple<FcitxWatcher*&>) ()
    at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#6  0x00007ffff2075dea in std::__detail::_Hash_node<std::pair<QWindow* const, FcitxQtICData>, false>* std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<QWindow* const, FcitxQtICData>, false> > >::_M_allocate_node<std::piecewise_construct_t const&, std::tuple<QWindow*&>, std::tuple<FcitxWatcher*&> >(std::piecewise_construct_t const&, std::tuple<QWindow*&>&&, std::tuple<FcitxWatcher*&>&&) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#7  0x00007ffff20745a1 in std::_Hashtable<QWindow*, std::pair<QWindow* const, FcitxQtICData>, std::allocator<std::pair<QWindow* const, FcitxQtICData> >, std::__detail::_Select1st, std::equal_to<QWindow*>, std::hash<QWindow*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_Scoped_node::_Scoped_node<std::piecewise_construct_t const&, std::tuple<QWindow*&>, std::tuple<FcitxWatcher*&> >(std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<QWindow* const, FcitxQtICData>, false> > >*, std::piecewise_construct_t const&, std::tuple<QWindow*&>&&, std::tuple<FcitxWatcher*&>&&) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#8  0x00007ffff2073429 in std::pair<std::__detail::_Node_iterator<std::pair<QWindow* const, FcitxQtICData>, false, false>, bool> std::_Hashtable<QWindow*, std::pair<QWindow* const, FcitxQtICData>, std::allocator<std::pair<QWindow* const, FcitxQtICData> >, std::__detail::_Select1st, std::equal_to<QWindow*>, std::hash<QWindow*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_emplace<std::piecewise_construct_t const&, std::tuple<QWindow*&>, std::tuple<FcitxWatcher*&> >(std::integral_constant<bool, true>, std::piecewise_construct_t const&, std::tuple<QWindow*&>&&, std::tuple<FcitxWatcher*&>&&) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#9  0x00007ffff20721b6 in std::pair<std::__detail::_Node_iterator<std::pair<QWindow* const, FcitxQtICData>, false, false>, bool> std::_Hashtable<QWindow*, std::pair<QWindow* const, FcitxQtICData>, std::allocator<std::pair<QWindow* const, FcitxQtICData> >, std::__detail::_Select1st, std::equal_to<QWindow*>, std::hash<QWindow*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::emplace<std::piecewise_construct_t const&, std::tuple<QWindow*&>, std::tuple<FcitxWatcher*&> >(std::piecewise_construct_t const&, std::tuple<QWindow*&>&&, std::tuple<FcitxWatcher*&>&&) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#10 0x00007ffff20708f0 in std::pair<std::__detail::_Node_iterator<std::pair<QWindow* const, FcitxQtICData>, false, false>, bool> std::unordered_map<QWindow*, FcitxQtICData, std::hash<QWindow*>, std::equal_to<QWindow*>, std::allocator<std::pair<QWindow* const, FcitxQtICData> > >::emplace<std::piecewise_construct_t const&, std::tuple<QWindow*&>, std::tuple<FcitxWatcher*&> >(std::piecewise_construct_t const&, std::tuple<QWindow*&>&&, std::tuple<FcitxWatcher*&>&&) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#11 0x00007ffff206c171 in QFcitxPlatformInputContext::createICData(QWindow*) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#12 0x00007ffff206a509 in QFcitxPlatformInputContext::setFocusObject(QObject*) () at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
#13 0x00007ffff6b90488 in QGuiApplicationPrivate::_q_updateFocusObject(QObject*) () at /usr/lib64/libQt6Gui.so.6
#14 0x00007ffff64e9ffb in ??? () at /usr/lib64/libQt6Core.so.6
#15 0x00007ffff6be9a22 in QWindow::focusObjectChanged(QObject*) () at /usr/lib64/libQt6Gui.so.6
#16 0x00007ffff774ffb3 in QWidget::setFocus(Qt::FocusReason) () at /usr/lib64/libQt6Widgets.so.6
#17 0x00007ffff77519b7 in QApplicationPrivate::setActiveWindow(QWidget*) () at /usr/lib64/libQt6Widgets.so.6
#18 0x00007ffff7751b35 in QApplicationPrivate::notifyActiveWindowChange(QWindow*) () at /usr/lib64/libQt6Widgets.so.6
#19 0x00007ffff6b9f417 in QGuiApplicationPrivate::processFocusWindowEvent(QWindowSystemInterfacePrivate::FocusWindowEvent*) () at /usr/lib64/libQt6Gui.so.6
#20 0x00007ffff6bf345c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt6Gui.so.6
#21 0x00007ffff6f94d00 in ??? () at /usr/lib64/libQt6Gui.so.6
#22 0x00007ffff5112e94 in g_main_dispatch () at /usr/lib64/libglib-2.0.so.0
#23 0x00007ffff5115f27 in g_main_context_iterate_unlocked.isra () at /usr/lib64/libglib-2.0.so.0
#24 0x00007ffff511651c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#25 0x00007ffff62e6f6c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt6Core.so.6
#26 0x00007ffff6529832 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt6Core.so.6
#27 0x00007ffff65299d6 in QCoreApplication::exec() () at /usr/lib64/libQt6Core.so.6
#28 0x0000555555561ab8 in main ()
```

**Comment by wengxt** [comment]
not surprise, you need to build against the qt used by qt creator

Best option: Use qt creator from your linux distribution, not from qt offical site, and NEVER blindly copy plugin into a different qt.

You may also QT_IM_MODULE=ibus or Wayland native protocol if you're on wayland.
